### ISSUE TITLE
Harvester call to getSpawn().availableEnergy() fails

### ISSUE THREAD

**Issue by MHarris021** [gdborton/screeps#3]
I've been testing out your code base in Screeps and I noticed that the logic called when  a Harvester is full fails with an undefined call to this.getSpawn().availableEnergy() if there are 0 couriers in a room. I traced through the code, and it appears that the spawn being returned is an object of StructureSpawn and not an object of Spawn defined in your code base. I believe that this may be a problem in your code in either the way you reassign structures to the enhanced versions or that the getSpawn() method in the Base creep class is returning the old unenhanced class. I'm not sure which. Changing the call to this.room.energyAvailable fixes the bug but may not the correct logical fix.

**Comment by gdborton** [comment]
Thanks for filing this!  I just updated the script to expose an enhance function on all built in structures and Creeps. Then I changed the return of getSpawn to return `spawn.enhance()`
